### ISSUE TITLE
TypeError Bad argument

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/gh-clone#1]
Because of incoming `''` (empty string) as first argument to the spawn in lib/spwan.js #L6

```
child_process.js:1121
  var err = this._handle.spawn(options);
                         ^
TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (child_process.js:1121:26)
    at exports.spawn (child_process.js:980:9)
    at Object.<anonymous> (/home/charlike/dev/gitclone.js:24:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:124:16)
```

I just rewrite it. I think there's no need of `lodash`, maybe only `verbalize` for UX, LOL :D

``` js
var spawn = require('child_process').spawn
var argv = require('minimist')(process.argv.slice(2));

var repo    = argv._[0] || argv.r || argv.repo;
var dest    = argv._[1] || argv.d || argv.dest;
var branch  = argv._[2] || argv.b || argv.branch;
var ssh     = argv._[3] || argv.s || argv.ssh;

function clone(ssh, repository, destination, branch) {
  var url = ssh ? 'git@github.com:' : 'https://github.com/'
  url = url + repository + '.git';

  var command = ['clone', url];

  if (destination) {command.push(destination)}
  if (branch) {command.concat(['-b', branch])}

  return command;
}

var args = clone(ssh, repo, dest, branch);

var proc = spawn('git', args, {
  stdio: 'inherit'
})

proc.on('exit', function (code) {
  process.exit(code)
})
```

**Comment by jonschlinkert** [comment]
that's great, thanks! I haven't been feeling well so I'm a little behind, give me a couple days and I'll get this all merged in. feel free to ping me to remind me! thanks!

**Comment by tunnckoCore** [comment]
too old, think can close lol
